Fft5woosh
sweIhm-ws2018-19/skillproject-fr-33 pull request #44
Opened 2018-12-07 16:12 UTC by fft5woosh

New Names for players

2018-12-08 17:17 UTC, Bergmaier requested changes

2018-12-08 17:17 UTC, Bergmaier commented on src/main/java/quiz/model/Question.java
> +	public String getInfo() { return info; } // info
Not strictly necessary as the attribute is `public` anyway, but why not.

2018-12-08 17:17 UTC, Bergmaier commented on src/main/java/quiz/model/QuizRound.java
> +						+ " Ladies first! Auf geht's, Heidi!");
Das funktioniert so nicht, wenn man erst die Spieleranzahl eingibt und erst danach die Region. "Auf gehts" (und ähnliche Äußerungen in den anderen Fällen) sind dann fehl am Platze. Das bitte erst (und nur) bei `if (isComplete) askQuestion()` ausgeben.

2018-12-08 17:17 UTC, Bergmaier commented on src/main/java/quiz/model/QuizRound.java
> +		//	players[i] = new Player("Spieler "+(i+1), 0);
Bitte löschen, das brauchen wir nicht mehr.

2018-12-08 17:17 UTC, Bergmaier commented on src/main/java/quiz/model/QuizRound.java
> +			speechText.append(players[asked % players.length].name);
Nein, so war das nicht gedacht. Bei nur einem Spieler soll *gar kein* Name ausgegeben werden. Auch nicht wenn es der leere String ist.

Die Bedingung kann `players.length` mit `1` vergleichen, besser aber wäre es den `name` auf `isEmpty` zu überprüfen. Die Logik, *ob und welche* Spielernamen bei welcher Zahl von Spielern ausgegeben werden findet sich dann nur in `createPlayers`. Dafür war der leere String gedacht.

2018-12-08 17:17 UTC, Bergmaier commented on src/main/java/quiz/model/QuizRound.java
> +		speechText.append(answer.isCorrect ? praise+"! "+ askedQuestions[lastAsked].getInfo() : "Falsch! ");
So wie ich das Issue verstanden habe, soll die Info immer ausgegeben werden, egal ob richtig oder falsch beantwortet. Bitte klären und fixen.

2018-12-08 17:17 UTC, Bergmaier commented on src/test/java/quiz/QuestionTest.java
> +		},"");
Schreib doch gleich noch einen Test dafür und setze den Parameter auf `"info"`.

2018-12-09 13:30 UTC, Bergmaier commented
Was ist mit den Infos zur Ostsee aus #35 ?

2018-12-09 18:27 UTC, fft5woosh commented
Kommt noch.

2018-12-10 21:26 UTC, Bergmaier approved these changes
Looks good now :-)

2018-12-10 21:26 UTC, Bergmaier commented on src/main/java/quiz/handlers/SelectAnswerIntentHandler.java
> +import javax.swing.event.ListSelectionEvent;
???

2018-12-10 21:26 UTC, Bergmaier commented on src/main/java/quiz/model/QuizRound.java
> +					 break;
Hier wäre **wirklich** eine Schleife angebracht.

2018-12-10 21:27 UTC, Bergmaier commented
Klicke "Merge pull request" (wenn du dich traust :-P )

2018-12-10 23:04 UTC, merged